### ISSUE TITLE
search for categoryKey nosuckMethod api 45

### ISSUE THREAD

**Issue by Isaacs9** [seatsio/seatsio-java#11]
Hi,
NoSuckMethodError api 45 in chartsReports.byCategoryKey

Severe: Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: seatsio.reports.charts.ChartReports.byCategoryKey(Ljava/lang/String;)Ljava/util/Map;] with root cause
java.lang.NoSuchMethodError: seatsio.reports.charts.ChartReports.byCategoryKey(Ljava/lang/String;)Ljava/util/Map.

I would like to contribute to the project. 
I would like to write a lib in kotlin as well.

Regards,

**Comment by mroloux** [comment]
Hi, how exactly did you manage to trigger this error? Could you provide a code sample please?
