### ISSUE TITLE
Google Guava depedency resolution issue

### ISSUE THREAD

**Issue by Ketul3012** [seatsio/seatsio-java#185]
While trying to add latest version of dependency in project, build is failing with reason that Google Guava is not able to choose between android and java version of library.

![image](https://github.com/seatsio/seatsio-java/assets/38484739/364794b4-4b34-4591-88ce-e9773217dec1)

I tried to exclude dependency and add java version manually but it is not working.

if someone has found solution to this Can you please help me with that?

Thank you so much.

**Comment by mroloux** [comment]
Hi,

Good point, we actually don't need guava anymore. It's gone in https://github.com/seatsio/seatsio-java/releases/tag/v82.16.0

**Comment by mroloux** [comment]
... actually it looks like releasing failed. We'll have a look at that.

**Comment by mroloux** [comment]
Should be ok now 👍

**Comment by Ketul3012** [comment]
Thanks @mroloux  for your help
